### ISSUE TITLE
Add vRealize Network Insight

### ISSUE THREAD

**Issue by khayama-zz** [ibm-cloud-docs/vmware#5]
Add vRealize Network Insight

![image](https://user-images.githubusercontent.com/13445142/43881669-e3fd95de-9be7-11e8-872d-c770f6ffe9e4.png)

**Comment by jmilst** [comment]
Can you please elaborate on what you want added to the documentation? Thanks!

**Comment by khayama-zz** [comment]
You don't have the description about "vRealize Network Insight" as you can see in the attached file.
Why don't you add this product license information to the article?

**Comment by jmilst** [comment]
@khayama My apologies for not understanding. Is a description missing in the user interface or in the IBM Cloud user documentation (https://console.bluemix.net/docs/)? If in the documentation, I need to know where - can you please share the web link of what you are looking at.

**Comment by khayama-zz** [comment]
You should know where the content is.
Please check it our at your side carefully but I put some link I have found.

https://console.bluemix.net/docs/infrastructure/vmware/vmware-vsphere-6.html#vmware-licensing-options
https://console.bluemix.net/docs/infrastructure/vmware/order-vmware-licenses.html#ordering-vmware-licenses

**Comment by jmilst** [comment]
Thank you for the information. I will check it out carefully.

**Comment by jmilst** [comment]
updated documentation
