### ISSUE TITLE
Updating QuantaStor Documentation

### ISSUE THREAD

**Issue by scottarenson** [ibm-cloud-docs/vmware#6]
Some of the content is outdated based QuantaStor 5.3. Can OSNEXUS help update this document?

**Comment by williamrocca-osnexus** [comment]
Echoing Scott's request.  Seeking assistance from the owner of this Github content.  Thanks, William

**Comment by jmilst** [comment]
@scottarenson @williamrocca-osnexus 
Apologies for the delay! Would you guys mind elaborating on what I can update with QuantaStor 5.3?
